### ISSUE TITLE
Apply TypeScript type definitions throughout application

### ISSUE THREAD

**Issue by qisforq** [AthletiFi/athletifi-website#31]
Ensure proper type definitions are applied and enforced across all TypeScript files.
- [x] **Update Type Definitions in Utility Functions** - Update `src/utils/helpers.ts` and `src/utils/seoConfig.ts` with proper TypeScript type definitions.
- [ ] **Enforce Type Definitions in Components** - Add types in common components like `src/components/common/Backtotop.tsx`, `src/components/common/Header.tsx`, and all components in `src/components/about-us/`.
- [x] **Type Definitions in API Handlers** - Define types for parameters and return values in `src/components/common/api/Api.tsx` and `src/components/common/api/ApiHelper.tsx`.
- [ ] **Update Pages with TypeScript Definitions** - Ensure proper types in pages like `src/pages/index.tsx`, `src/pages/about-us.tsx`, and convert `src/pages/news/[slug].js` to TypeScript with types.
- [x] **Review and Update TypeScript Configurations** - Check and adjust configurations in `tsconfig.json` for stricter type checking.
- [x] **Implement Type Definitions in Contexts/Hooks** - Add TypeScript types in contexts and hooks within `src/contexts/` and `src/hooks/`.

**Comment by chef-louis** [comment]
@HectorAgudelo Since the project is already configured for typescript, I don't think we need to do anything else for setup. I'll start from the top of the list of sub-tasks and work my way down. Feel free to take any when you get time for it. Also I'm not sure but there may be more typescript implementation to be done throughout the project so we can review after knocking off the list here.

**Comment by HectorAgudelo** [comment]
Sounds good

**Comment by qisforq** [comment]
You can find the schemas from Strapi here: https://github.com/AthletiFi/athletifi-website-cms/tree/main/src/api
