### ISSUE TITLE
Set Up Amazon RDS PostgreSQL Database Instance

### ISSUE THREAD

**Issue by qisforq** [AthletiFi/athletifi-website#95]
Note: this is a dependency task of #94 

### Objective
The goal of this task is to create and configure an Amazon RDS instance running PostgreSQL to host our application's database. We have a predefined database schema designed using pgModeler, which needs to be implemented in this new RDS instance.

### Prerequisites
- Ensure that you have access to the AWS Management Console with the necessary permissions to create an RDS instance.
- Obtain the database schema file from pgModeler.

#### Step 1: Create RDS PostgreSQL Instance
- Navigate to the Amazon RDS console and begin the process to create a new RDS database instance.
- Select PostgreSQL as the database engine.
- Choose the appropriate DB instance size according to the expected workload.
- Configure storage settings, ensuring that storage autoscaling is enabled to handle load dynamically.
- Set up the DB instance identifier, master username, and a secure master password.

#### Step 2: Configure Network and Security
- Select or create a new VPC where the RDS instance will reside.
- Ensure that the DB instance is placed in a private subnet if it doesn’t need direct public access.
- Configure the security group to allow traffic only from the application layer and management IPs.
- Ensure that the database is not publicly accessible and that encryption at rest is enabled.

#### Step 3: Database Options
- Set the initial database name to match the schema design from pgModeler.
- Choose the appropriate parameter group that matches the PostgreSQL version used in the schema design.
- Set up automated backups, database replication (if needed for high availability), and maintenance windows according to our operational policies.

#### Step 4: Launch the Instance
- Review all settings and launch the instance.
- Monitor the instance creation process via the RDS dashboard.

#### Step 5: Schema Implementation
- Once the instance is up and running, use the PostgreSQL schema file from pgModeler to implement the database schema.
- Validate that the schema has been implemented correctly by connecting to the database instance and running a series of test queries.

**Comment by chef-louis** [comment]
Including update request from @qisforq:

Hey Louis/Hector, I added two new columns to the database after speaking to Paula earlier:
 

1. We added player_avatar_url to the players_team_info table, to store a headshot version of the player's image for thumbnails.
2. We added gender to the player_identities table. gender will have a custom enum type to only accept male, female or x (I chose X because that's the [third option allowed on US passports](https://travel.state.gov/content/travel/en/passports/need-passport/selecting-your-gender-marker.html#:~:text=You%20can%20select%20male%20(M,for%20routine%20or%20expedited%20service.) now)
